apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-server
spec:
  selector:
    matchLabels:
      app: customer-server
  replicas: 1
  template:
    metadata:
      labels:
        swck-java-agent-injected: "true"
        app: customer-server
    spec:
      # Skywalking start
      volumes:
        - name: skywalking-agent
          emptyDir: { }

      initContainers:
        - name: agent-container
          image: apache/skywalking-java-agent:8.7.0-alpine
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      # Skywalking end

      containers:
        - name: customer-server
          image: "wisekingdavid/customer-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-customer
              containerPort: 9200
          #          imagePullSecrets:
          #            - name: image-secret

          # Skywalking start
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/skywalking/agent/skywalking-agent.jar"
            - name: SW_AGENT_NAME
              value: "customer-server"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "127.0.0.1:11800"
              # Skywalking end

          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-server-service
spec:
  selector:
    app: customer-server
  ports:
    - name: "http"
      protocol: "TCP"
      port: 9200
      targetPort: 9200





