# Author
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-server
spec:
  selector:
    matchLabels:
      app: author-server
  replicas: 1
  template:
    metadata:
      labels:
        app: author-server
    spec:
      containers:
        -
        - name: author-server
          image: "wisekingdavid/author-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-author
              containerPort: 9000

          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 300
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: author-server
spec:
  selector:
    app: author-server
  ports:
    - name: http-traffic
      port: 9000
      targetPort: http-author


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: author-server
  labels:
    heritage: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app: author-server
  jobLabel: author-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /actuator/prometheus
      port: http-traffic
      scheme: http
      interval: 30s


#  Book
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-server
spec:
  selector:
    matchLabels:
      app: book-server
  replicas: 1
  template:
    metadata:
      labels:
        app: book-server
    spec:
      containers:
        -
        - name: book-server
          image: "wisekingdavid/book-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-book
              containerPort: 9100

          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9100
            initialDelaySeconds: 300
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: book-server
spec:
  selector:
    app: book-server
  ports:
    - name: http-traffic
      port: 9100
      targetPort: http-book


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: book-server
  labels:
    heritage: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app: book-server
  jobLabel: book-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /actuator/prometheus
      port: http-traffic
      scheme: http
      interval: 30s


#  Admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        -
        - name: admin-server
          image: "wisekingdavid/admin-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-admin
              containerPort: 9300

          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9300
            initialDelaySeconds: 300
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - name: http-traffic
      port: 9000
      targetPort: http-admin


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin-server
  labels:
    heritage: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app: admin-server
  jobLabel: admin-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /actuator/prometheus
      port: http-traffic
      scheme: http
      interval: 30s


#  Customer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-server
spec:
  selector:
    matchLabels:
      app: customer-server
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-server
    spec:
      containers:
        -
        - name: customer-server
          image: "wisekingdavid/customer-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-customer
              containerPort: 9200

          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9200
            initialDelaySeconds: 300
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: customer-server
spec:
  selector:
    app: customer-server
  ports:
    - name: http-traffic
      port: 9000
      targetPort: http-customer


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-server
  labels:
    heritage: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app: customer-server
  jobLabel: customer-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /actuator/prometheus
      port: http-traffic
      scheme: http
      interval: 30s
