version: '3'


services:

  admin-server:
    image: wisekingdavid/admin-server:latest
    container_name: admin-server
    ports:
      - "9300:9300"
    depends_on:
    - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/admin-postgres-db
      - SPRING_DATASOURCE_USERNAME=admin-postgres
      - SPRING_DATASOURCE_PASSWORD=admin-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  PostgreSQL:
    image: postgres
    container_name: admin-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin-postgres
      - POSTGRES_PASSWORD=admin-postgres
      - POSTGRES_DB=admin-postgres-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    depends_on:
      - admin-server


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: root
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=host.docker.internal
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
    ports:
      - '3000:3000'
    depends_on:
      - prometheus




