apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-server
spec:
  selector:
    matchLabels:
      app: author-server
  replicas: 1
  template:
    metadata:
      labels:
        app: author-server
    spec:
      containers:
        -
        - name: author-server
          image: "wisekingdavid/author-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-author
              containerPort: 9000

          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 300
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: author-server
spec:
  selector:
    app: author-server
  type: ClusterIP
  ports:
    - name: http-traffic
      port: 9000
      targetPort: http-author


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: author-server
  labels:
    heritage: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app: author-server
  jobLabel: author-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /actuator/prometheus
      port: http-traffic
      scheme: http
      interval: 30s


